# Generated by Django 4.0.6 on 2022-07-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_price_inventory_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventories'},
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit_measure',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
