# Generated by Django 4.0.6 on 2022-07-23 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_options_inventory_unit_measure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='unit_measure',
            new_name='measure_unit',
        ),
    ]
