# Generated by Django 4.0.6 on 2022-07-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_unit_measure_inventory_measure_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='measure_unit',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
